//HEADER FILES
#include<stdio.h>
#include<stdlib.h>
#include<time.h>
#include<assert.h>
#include<string.h>

#define HASH(N, K) ( N % K )

//ENTRY POINT OF ALL FUNCTIONS
int main(int argc, char*argv[]) {

	unsigned long long int num;
	assert(argc == 3);
	int k = atoi(argv[1]); //K is total number of buckets/ slots 
	int nr_elements = atoi(argv[2]); //nr_element is total number of elements
	int* arr = (int*)malloc(nr_elements * sizeof(int));
	memset(arr, 0, nr_elements * sizeof(int));

	srand(time(0));

	//Inserting an random element to its bucket number( key )
	for (int i = 0; i < nr_elements; i++) {
		int key = HASH(rand(), k);
		arr[key] = arr[key] + 1; 
		//If key generated by hash function is same, then it is increment by 1
	}

	//Number of element in a bucket 
	for (int i = 0; i < k; i++)
		printf("Modulo(%d) : %d\n", i, arr[i]);

	free(arr);
	return EXIT_SUCCESS;
}